import { Product } from './types';

// Lista completa de colores disponibles - Más de 100 tonalidades
const ALL_COLORS = [
  // Blancos y Grises
  'Blanco', 'Blanco Hueso', 'Marfil', 'Gris Perla', 'Gris Plata', 'Gris Claro', 
  'Gris', 'Gris Medio', 'Gris Oscuro', 'Carbón', 'Gris Grafito', 'Negro',
  
  // Marrones y Beiges
  'Beige', 'Arena', 'Caqui', 'Camel', 'Marrón Claro', 'Marrón', 
  'Café', 'Chocolate', 'Marrón Oscuro',
  
  // Azules - Desde claros hasta oscuros
  'Azul Hielo', 'Azul Cielo', 'Azul Claro', 'Azul Celeste', 'Azul Pavo Real', 
  'Azul', 'Azul Royal', 'Azul Eléctrico', 'Azul Cobalto', 'Azul Francia', 
  'Azul Marino', 'Azul Petróleo', 'Navy', 'Azul Oscuro', 'Índigo',
  
  // Cyan y Turquesas - Tonos vibrantes
  'Cyan', 'Aqua', 'Turquesa', 'Turquesa Claro', 'Verde Azulado', 'Teal',
  'Turquesa Vibrante', 'Aqua Neón', 'Celeste Brillante',
  
  // Verdes - Desde neón hasta oscuros
  'Verde Menta', 'Verde Lima', 'Verde Neón', 'Verde Claro', 'Verde Kelly', 
  'Verde', 'Verde Pasto', 'Verde Esmeralda', 'Verde Militar', 'Verde Bosque', 
  'Verde Oliva', 'Verde Oscuro', 'Verde Musgo', 'Lima Brillante', 'Verde Fluorescente',
  
  // Amarillos - Vibrantes y brillantes
  'Amarillo Neón', 'Amarillo', 'Amarillo Limón', 'Amarillo Claro', 
  'Amarillo Canario', 'Dorado', 'Amarillo Mostaza', 'Amarillo Oscuro',
  'Amarillo Fluorescente', 'Amarillo Brillante',
  
  // Naranjas - Desde pastel hasta neón
  'Naranja Neón', 'Naranja Claro', 'Naranja', 'Naranja Fuego', 
  'Naranja Quemado', 'Mandarina', 'Calabaza', 'Melocotón',
  'Naranja Brillante', 'Naranja Fluorescente',
  
  // Rojos - Desde rosa coral hasta vino
  'Rosa Coral', 'Coral', 'Salmón', 'Rojo Claro', 'Rojo', 'Rojo Fuego', 
  'Rojo Sangre', 'Carmesí', 'Rojo Oscuro', 'Granate', 'Borgoña', 'Vino',
  'Rojo Brillante', 'Rojo Vibrante',
  
  // Rosas - Desde pastel hasta neón
  'Rosa Claro', 'Rosa Pastel', 'Rosa', 'Rosa Chicle', 'Rosa Fuerte', 
  'Fucsia', 'Magenta', 'Rosa Mexicano', 'Rosa Neón', 'Rosa Fluorescente',
  'Fucsia Vibrante', 'Rosa Brillante', 'Rosa Intenso',
  
  // Morados y Púrpuras - Desde lavanda hasta ciruela
  'Lavanda', 'Lila', 'Morado Claro', 'Orquídea', 'Púrpura', 
  'Morado', 'Violeta', 'Morado Oscuro', 'Berenjena', 'Ciruela',
  'Morado Vibrante', 'Púrpura Brillante', 'Violeta Intenso',
  
  // Colores Adicionales Vibrantes
  'Lima Eléctrico', 'Fucsia Eléctrico', 'Azul Eléctrico Brillante',
  'Verde Manzana', 'Menta Brillante', 'Coral Brillante',
];

// Paleta de colores para todas las camisetas basada en el catálogo
const TSHIRT_COLOR_PALETTE = [
  '#654321', '#008B8B', '#0000FF', '#00CED1', '#8B0000', '#FFFF00',
  '#E6E6FA', '#FF69B4', '#2F4F4F', '#FFFF00', '#FFA500', '#D2691E',
  '#FFFFFF', '#808080', '#D3D3D3', '#FFB6C1', '#C0C0C0', '#F5DEB3',
  '#FF00FF', '#4B0082', '#98FF98', '#FFFFFF', '#FF1493', '#8B4513',
  '#8B0000', '#2F4F4F', '#FF0000', '#D2691E', '#654321', '#00CED1',
  '#FFA500', '#C0C0C0', '#FFA500', '#00CED1', '#87CEEB', '#FF0000',
  '#FFFFFF', '#808080', '#C0C0C0', '#696969', '#000000',
];

export const mockProducts: Product[] = [
  // Men's T-Shirts
  {
    id: 'men-tshirt-1',
    name: 'Camiseta Negra Esencial',
    category: 'men',
    subcategory: 't-shirts',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'figma:asset/3edfcbe2488a990551ef8f07bf37216234ab1e88.png',
    images: [
      'figma:asset/3edfcbe2488a990551ef8f07bf37216234ab1e88.png',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    ],
    description: 'Camiseta de algodón premium de peso pesado con ajuste moderno',
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ALL_COLORS,
    colorPalette: TSHIRT_COLOR_PALETTE,
    stock: 150,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    featured: true,
    trending: true,
  },
  {
    id: 'men-tshirt-2',
    name: 'Camiseta Negra Oversize',
    category: 'men',
    subcategory: 't-shirts',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800',
    images: ['https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800'],
    description: 'Ajuste oversize relajado para el máximo estilo urbano',
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ALL_COLORS,
    colorPalette: TSHIRT_COLOR_PALETTE,
    stock: 100,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    trending: true,
  },
  {
    id: 'men-tshirt-3',
    name: 'Camiseta Premium con Bolsillo',
    category: 'men',
    subcategory: 't-shirts',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=800',
    images: ['https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=800'],
    description: 'Camiseta clásica con bolsillo y mezcla de algodón premium',
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ALL_COLORS,
    colorPalette: TSHIRT_COLOR_PALETTE,
    stock: 120,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
  },

  // Men's Polos
  {
    id: 'men-polo-1',
    name: 'Polo Negro Clásico',
    category: 'men',
    subcategory: 'polos',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1626497764746-6dc36546b388?w=800',
    images: ['https://images.unsplash.com/photo-1626497764746-6dc36546b388?w=800'],
    description: 'Polo sofisticado con ajuste atlético moderno',
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 80,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    featured: true,
  },

  // Men's Hoodies
  {
    id: 'men-hoodie-1',
    name: 'Sudadera Negra Premium',
    category: 'men',
    subcategory: 'hoodies',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'figma:asset/5bcb7a4e555b26bf97b5d76cc092fa0530f59c29.png',
    images: ['figma:asset/5bcb7a4e555b26bf97b5d76cc092fa0530f59c29.png'],
    description: 'Sudadera de felpa pesada con bolsillo canguro',
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 90,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    featured: true,
    trending: true,
  },
  {
    id: 'men-hoodie-2',
    name: 'Sudadera Urbana Oversize',
    category: 'men',
    subcategory: 'hoodies',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800',
    images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800'],
    description: 'Ajuste oversize con hombros caídos',
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 75,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
  },

  // Men's Joggers
  {
    id: 'men-jogger-1',
    name: 'Joggers Negros Esenciales',
    category: 'men',
    subcategory: 'joggers',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=800',
    images: ['https://images.unsplash.com/photo-1517438476312-10d79c077509?w=800'],
    description: 'Joggers cómodos con ajuste cónico',
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 100,
    allowCustom: false,
    trending: true,
  },

  // Men's Hats
  {
    id: 'men-hat-1',
    name: 'Gorra Snapback',
    category: 'gorras',
    subcategory: 'hats',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800',
    images: ['https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800'],
    description: 'Snapback clásica con visera plana',
    sizes: ['Talla Única'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 120,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    featured: true,
  },

  // Women's T-Shirts
  {
    id: 'women-tshirt-1',
    name: 'Camiseta Negra Esencial Mujer',
    category: 'women',
    subcategory: 't-shirts',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800',
    images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800'],
    description: 'Camiseta ajustada premium con mezcla de algodón suave',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ALL_COLORS,
    colorPalette: TSHIRT_COLOR_PALETTE,
    stock: 130,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    trending: true,
  },
  {
    id: 'women-tshirt-2',
    name: 'Camiseta Oversize Mujer',
    category: 'women',
    subcategory: 't-shirts',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800',
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800'],
    description: 'Ajuste oversize relajado para estilo casual',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ALL_COLORS,
    colorPalette: TSHIRT_COLOR_PALETTE,
    stock: 110,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    featured: true,
  },

  // Women's Hoodies
  {
    id: 'women-hoodie-1',
    name: 'Sudadera Premium Mujer',
    category: 'women',
    subcategory: 'hoodies',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800'],
    description: 'Sudadera cómoda con ajuste moderno',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 95,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    featured: true,
  },

  // Women's Joggers
  {
    id: 'women-jogger-1',
    name: 'Joggers Cónicos Mujer',
    category: 'women',
    subcategory: 'joggers',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800',
    images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800'],
    description: 'Joggers elegantes con tobillo cónico',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 85,
    allowCustom: false,
  },

  // Gorras
  {
    id: 'gorras-hat-1',
    name: 'Snapback Premium',
    category: 'gorras',
    subcategory: 'hats',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'figma:asset/1b3b90e9f13e6f0bfe2e2ccee076db293bf3180e.png',
    images: ['figma:asset/1b3b90e9f13e6f0bfe2e2ccee076db293bf3180e.png'],
    description: 'Gorra snapback de alta calidad',
    sizes: ['Talla Única'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 100,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
  },
  {
    id: 'gorras-hat-2',
    name: 'Gorra Dad Hat',
    category: 'gorras',
    subcategory: 'hats',
    price: 9,
    retailPrice: 9,
    wholesalePrice: 6.5,
    image: 'figma:asset/1b3b90e9f13e6f0bfe2e2ccee076db293bf3180e.png',
    images: ['figma:asset/1b3b90e9f13e6f0bfe2e2ccee076db293bf3180e.png'],
    description: 'Gorra dad hat sin estructura con visera curva',
    sizes: ['Talla Única'],
    colors: ALL_COLORS,
    colorPalette: [],
    stock: 110,
    allowCustom: true,
    customPricing: {
      small: 2.5,
      medium: 4.0,
      large: 6.0,
    },
    trending: true,
  },
];